# -*- coding: utf-8 -*-
"""Chess Engine Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wIxQlVFnB0bemUX9iwOWT7AJnCc7nK2
"""

!python --version

!pip install requests

import requests
import json

username = "DrNykterstein"
url = f"https://lichess.org/api/games/user/{username}"

params = {
    "max" : 5,
    "clocks" : "true",
    "evals" : "true",
    "opening" : "true",
}

headers = {
    "Accept" : "application/x-ndjson"
}

response = requests.get(url, params=params, headers=headers)

print("Status code:", response.status_code)
print("-" * 50)

games = [json.loads(line) for line in response.text.strip().split("\n")]

print(f"Number of games: {len(games)}")
print("-" * 50)

print("Keys available in a single game object:")
print(list(games[0].keys()))
print("-" * 50)

print("Full first game (pretty-printed):")
print(json.dumps(games[0], indent=2)[:2000])

!pip install python-chess

import chess
import chess.pgn
import io

moves_string = "e4 Nf6 e5 Nd5 Nc3 Nxc3 dxc3 d6 Nf3 Nc6 Bb5 a6 Bxc6+ bxc6 O-O f6 exf6 exf6 Nd4 Qd7 Qh5+ g6 Qf3 Kf7 Nxc6 Bb7 Nd8+ Rxd8 Qxb7 Qb5 Qxc7+ Rd7 c4 Rxc7 cxb5 axb5 c3 Be7 Rd1 Ra8 a3 f5 Be3 Ke6 Rd3 Bf6 Rad1 Rc6 Bf4 Be5 Re1 Kf6 Bxe5+ dxe5 Rd5 e4 Rxb5 Rd6 g3 Rd2 c4 Rc2 c5 Rd8 Rb6+ Kg5 Rd6 Ra8 c6 Rxb2 Rc1 Rc8 c7 Rb7 Rdc6 Ra7 R1c3 f4 R6c5+ Kg4 gxf4 Kxf4 Kg2 g5 R5c4 Ke5 Rc5+ Kf4 f3 exf3+ Kf2 Ke4 R5c4+ Kf5 Kxf3 h5 Rc5+ Ke6 Rc6+ Kd7 Ke4 g4 Kd5 Ra5+ R6c5 Rxc7 Rxa5 Rxc3 Ke4 Rh3 Rd5+ Ke6 Rd2 Kf6 Kf4 Rf3+ Ke4 Rxa3 Kf4 Rf3+ Ke4 Kg5 Rg2 Kh4 Ke5 Kh3 Rd2 h4 Ke4 Rf8 Ke3 g3 hxg3 hxg3 Rd1 g2"
board = chess.Board()

move_list = moves_string.split()

print(f"Total moves in this snippet: {len(move_list)}")
print("-" * 50)

positions = []

for i, move_san in enumerate(move_list):
  turn = "white" if board.turn == chess.WHITE else "black"
  move = board.parse_san(move_san)
  board.push(move)

  positions.append({
      "move_number": i + 1,
      "player": turn,
      "move_san": move_san,
      "fen": board.fen()
  })

for pos in positions[:4]:
  print(pos)
  print()

!apt-get install -y stockfish

!which stockfish

import chess
import chess.engine

STOCKFISH_PATH = "/usr/games/stockfish"

engine = chess.engine.SimpleEngine.popen_uci(STOCKFISH_PATH)

fen = "rnbqkb1r/pppppppp/8/3nP3/8/8/PPPP1PPP/RNBQKBNR w KQkq - 0 3"
board = chess.Board(fen)

info = engine.analyse(board,chess.engine.Limit(depth=15))

score = info["score"]
best_line = info["pv"]

print("Raw score object:", score)
print("Best move found:", best_line[0])
print("Full best line (next few moves):", best_line[:5])

engine.quit()

import chess
import chess.engine
import pandas as pd

STOCKFISH_PATH = "/usr/games/stockfish"
DEPTH = 15

moves_string = games[0]["moves"]

engine = chess.engine.SimpleEngine.popen_uci(STOCKFISH_PATH)

def get_eval_cp(board, depth=DEPTH):
  info = engine.analyse(board, chess.engine.Limit(depth=depth))
  return info["score"].white().score(mate_score=100000)

board = chess.Board()
move_list = moves_string.split()

records = []
eval_before = get_eval_cp(board)

for i, move_san in enumerate(move_list):
  mover = "white" if board.turn == chess.WHITE else "black"

  move = board.parse_san(move_san)
  board.push(move)

  eval_after = get_eval_cp(board)

  if mover== "white":
    cp_loss = max(0, eval_before - eval_after)
  else:
    cp_loss = max(0, eval_after - eval_before)

  records.append({
      "move_number": i + 1,
      "player": mover,
      "move_san": move_san,
      "eval_before": eval_before,
      "eval_after": eval_after,
      "cp_loss": cp_loss,
  })

  eval_before = eval_after

engine.quit()

df = pd.DataFrame(records)
print(f"Total moves processed: {len(df)}")
df.head(10)

def classify_move(cp_loss):
  if cp_loss >= 300:
    return "blunder"
  elif cp_loss >= 100:
    return "mistake"
  elif cp_loss >= 50:
    return "inaccuracy"
  else:
    return "good"

df["classification"] = df["cp_loss"].apply(classify_move)

summary = df.groupby(["player", "classification"]).size().unstack(fill_value=0)
print(summary)

import time

def fetch_games(username, max_games=10):
    url = f"https://lichess.org/api/games/user/{username}"
    params = {
        "max": max_games,
        "clocks": "true",
        "evals": "true",
        "opening": "true",
        "rated": "true",
        "perfType": "blitz",
    }
    headers = {"Accept": "application/x-ndjson"}
    response = requests.get(url, params=params, headers=headers)

    # NEW: guard clause - don't attempt to parse anything unless the request
    # actually succeeded. This is what would've caught the earlier bug.
    if response.status_code != 200:
        print(f"[{username}] request failed - status {response.status_code}: {response.text}")
        return []

    games = [json.loads(line) for line in response.text.strip().split("\n") if line]
    print(f"[{username}] fetched {len(games)} games")
    return games

magnus_games = fetch_games("DrNykterstein", max_games=10)
time.sleep(3)
hikaru_games = fetch_games("TSMFTXH", max_games=10)

print(f"Magnus games fetched: {len(magnus_games)}")
print(f"Hikaru games fetched: {len(hikaru_games)}")

import chess
import chess.engine
import pandas as pd
import os
import time

STOCKFISH_PATH = "/usr/games/stockfish"
DEPTH = 15
OUTPUT_FILE = "chess_analysis_results.csv"

def classify_move(cp_loss):
  if cp_loss >= 300:
    return "blunder"
  elif cp_loss >= 100:
    return "mistake"
  elif cp_loss >= 50:
    return "inaccuracy"
  else:
    return "good"

def get_eval_cp(board,engine,depth=DEPTH):
  info = engine.analyse(board, chess.engine.Limit(depth=depth))
  return info["score"].white().score(mate_score=100000)

def analyse_game(game,target_username,engine):
  white_name = game["players"]["white"]["user"]["name"]
  black_name = game["players"]["black"]["user"]["name"]

  target_color = None
  if white_name.lower() == target_username.lower():
    target_color = "white"
  elif black_name.lower() == target_username.lower():
    target_color = "black"
  else:
    print(f" WARNING: {target_username} not found in game {game['id']}, skipping")
    return []

  board = chess.Board()
  move_list = game["moves"].split()
  eval_before = get_eval_cp(board, engine)

  records = []
  for i, move_san in enumerate(move_list):
    mover = "white" if board.turn == chess.WHITE else "black"

    move = board.parse_san(move_san)
    board.push(move)

    eval_after = get_eval_cp(board, engine)

    if mover == "white":
      cp_loss = max(0,eval_before - eval_after)
    else:
      cp_loss = max(0,eval_after - eval_before)

    if mover == target_color:
      records.append({
          "game_id": game["id"],
          "player_name": target_username,
          "player_color": target_color,
          "opponent_rating": game["players"]["black" if target_color == "white" else "white"]["rating"],
          "move_number": i + 1,
          "move_san": move_san,
          "eval_before": eval_before,
          "eval_after": eval_after,
          "cp_loss": cp_loss,
          "classification": classify_move(cp_loss),
      })

    eval_before = eval_after

  return records

engine = chess.engine.SimpleEngine.popen_uci(STOCKFISH_PATH)

all_batches = [
    ("DrNykterstein", magnus_games),
    ("TSMFTXH", hikaru_games),
]

file_exits = os.path.exists(OUTPUT_FILE)

for player_name, game_list in all_batches:
  for idx, game in enumerate(game_list):
    print(f"Analyzing {player_name} - game {idx + 1}/{len(game_list)} (id: {game['id']})..........")

    try:
      game_records = analyse_game(game, player_name, engine)
      df_chunk = pd.DataFrame(game_records)

      df_chunk.to_csv(OUTPUT_FILE, mode="a", header=not file_exits, index=False)
      file_exits = True

      print(f"  -> saved {len(df_chunk)} moves")
    except Exception as e:
      print(f"  -> FAILED on game  {game['id']} {e}")
      continue

engine.quit()
print("\nDone! Results saved to", OUTPUT_FILE)

import pandas as pd

df = pd.read_csv("chess_analysis_results.csv")

print(f"Total rows: {len(df)}")
print(df["player_name"].value_counts())
print("-"*50)

summary = df.groupby(["player_name","classification"]).size().unstack(fill_value=0)
print(summary)
print("-"*50)

summary_pct = summary.div(summary.sum(axis=1),axis=0)*100
print(summary_pct.round(1))
print("-"*50)

avg_cpl = df.groupby("player_name")["cp_loss"].mean()
print("Average centipawn loss per game:")
print(avg_cpl.round(1))

# Look at the most extreme centipawn-loss values per player
print("Top 5 highest cp_loss moves - Magnus:")
print(df[df["player_name"] == "DrNykterstein"].nlargest(5, "cp_loss")[["game_id", "move_number", "move_san", "cp_loss"]])
print()
print("Top 5 highest cp_loss moves - Hikaru:")
print(df[df["player_name"] == "TSMFTXH"].nlargest(5, "cp_loss")[["game_id", "move_number", "move_san", "cp_loss"]])
print()

# Median is far less sensitive to outliers than mean - a better "typical move" summary
median_cpl = df.groupby("player_name")["cp_loss"].median()
print("Median centipawn loss (more robust to outliers):")
print(median_cpl)

CP_LOSS_CAP = 1000

df["cp_loss_capped"] = df["cp_loss"].clip(upper=CP_LOSS_CAP)

avg_cpl_capped = df.groupby("player_name")["cp_loss_capped"].mean()
print("Average centipawn loss (capped at 1000):")
print(avg_cpl_capped.round(1))

import re
import pandas as pd

df = pd.read_csv("chess_analysis_results.csv")

def extract_square(move_san):
    move_san = move_san.strip()
    if move_san in ("O-O", "O-O+", "O-O#", "O-O-O", "O-O-O+", "O-O-O#"):
        return None
    match = re.search(r"([a-h][1-8])", move_san)
    return match.group(1) if match else None

df["square"] = df["move_san"].apply(extract_square)
errors = df[df["classification"].isin(["inaccuracy", "mistake", "blunder"])]
square_counts = errors["square"].value_counts()

print(square_counts.to_dict())

"""**TIME PRESSURE**"""

import pandas as pd

df = pd.read_csv("chess_analysis_results.csv")

clocks_lookup = {}
for g in magnus_games + hikaru_games:
  clocks_lookup[g["id"]] = g.get("clocks", [])

def get_clock_seconds(row):
  clocks = clocks_lookup.get(row["game_id"], [])
  if idx < len(clocks):
    return clocks[idx] / 100
  return None

df["clock_seconds"] = df.apply(get_clock_seconds, axis=1)

print(f"Rows with clock data: {df['clock_seconds'].notna().sum()} / {len(df)}")
print(df[["game_id", "move_number", "move_san", "cp_loss", "clock_seconds"]].head(10))

raw_clocks = clocks_lookup.get("kAdOQKeh",[])
print("Length of clocks array:", len(raw_clocks))
print("First 20 raw clock values:", raw_clocks[:20])

sample = df[df["game_id"] == "kAdOQKeh"]
sample["computed_idx"] = sample["move_number"] - 1
print(sample[["move_number", "clock_seconds", "computed_idx"]])

clocks_lookup = {}
for g in magnus_games + hikaru_games:
  clocks_lookup[g["id"]] = g.get("clocks", [])

def get_clock_seconds(row):
  clocks = clocks_lookup.get(row["game_id"], [])
  idx = row["move_number"] - 1
  if 0 <= idx < len(clocks):
    return clocks[idx] / 100
  return None

df["clock_seconds"] = df.apply(get_clock_seconds, axis=1)

print(df[df["game_id"] == "kAdOQKeh"][["move_number", "clock_seconds"]].head(10))

def time_pressure_bucket(seconds):
  if seconds is None:
    return None
  elif seconds >= 60:
    return "comfortable (60s+)"
  elif seconds >= 30:
    return "getting low (30-60s)"
  elif seconds >= 10:
    return "low (10-30s)"
  else:
    return "critical (<10s)"

df["time_bucket"] = df["clock_seconds"].apply(time_pressure_bucket)

bucket_order = ["comfortable (60s+)", "getting low (30-60s)", "low (10-30s)", "critical (<10s)"]

counts = df.groupby(["player_name","time_bucket"]).size().reindex(
    pd.MultiIndex.from_product([df["player_name"].unique(), bucket_order]),
    fill_value=0
)
print("Move counts per bucket:")
print(counts)
print("-"*50)

avg_by_bucket = df.groupby(["player_name", "time_bucket"])["cp_loss"].mean().reindex(
    pd.MultiIndex.from_product([df["player_name"].unique(), bucket_order]),
    fill_value=0
)
print("Average centipawn loss per bucket:")
print(avg_by_bucket.round(1))

CP_LOSS_CAP = 1000
df["cp_loss_capped"] = df["cp_loss"].clip(upper=CP_LOSS_CAP)

df.to_csv("chess_analysis_results.csv", index=False)

avg_by_bucket_capped = df.groupby(["player_name", "time_bucket"])["cp_loss_capped"].mean().reindex(
    pd.MultiIndex.from_product([df["player_name"].unique(), bucket_order]), fill_value=None
)
print("Average centipawn loss per bucket (capped):")
print(avg_by_bucket_capped.round(1))

median_by_bucket = df.groupby(["player_name", "time_bucket"])["cp_loss"].median().reindex(
    pd.MultiIndex.from_product([df["player_name"].unique(), bucket_order]), fill_value=None
)
print("\nMedian centipawn loss per bucket:")
print(median_by_bucket.round(1))

magnus_games_v2 = fetch_games("DrNykterstein", max_games=30)
time.sleep(3)
hikaru_games_v2 = fetch_games("TSMFTXH", max_games=30)

print(f"Magnus games fetched: {len(magnus_games_v2)}")
print(f"Hikaru games fetched: {len(hikaru_games_v2)}")

OUTPUT_FILE_V2 = "chess_analysis_results_v2.csv"

engine = chess.engine.SimpleEngine.popen_uci(STOCKFISH_PATH)

all_batches_v2 = [
    ("DrNykterstein", magnus_games_v2),
    ("TSMFTXH", hikaru_games_v2),
]

file_exists = os.path.exists(OUTPUT_FILE_V2)

for player_name, game_list in all_batches_v2:
    for idx, game in enumerate(game_list):
        print(f"Analyzing {player_name} - game {idx + 1}/{len(game_list)} (id: {game['id']})...")
        try:
            game_records = analyse_game(game, player_name, engine)
            df_chunk = pd.DataFrame(game_records)
            df_chunk.to_csv(OUTPUT_FILE_V2, mode="a", header=not file_exists, index=False)
            file_exists = True
            print(f"  -> saved {len(df_chunk)} moves")
        except Exception as e:
            print(f"  -> FAILED on game {game['id']}: {e}")
            continue

engine.quit()
print("\nDone! Results saved to", OUTPUT_FILE_V2)

import pandas as pd

df2 = pd.read_csv("chess_analysis_results_v2.csv")
print(f"Total rows: {len(df2)}")
print(df2["player_name"].value_counts())

clocks_lookup_v2 = {}
for g in magnus_games_v2 + hikaru_games_v2:
    clocks_lookup_v2[g["id"]] = g.get("clocks", [])

def get_clock_seconds_v2(row):
    clocks = clocks_lookup_v2.get(row["game_id"], [])
    idx = row["move_number"] - 1
    if 0 <= idx < len(clocks):
        return clocks[idx] / 100
    return None

df2["clock_seconds"] = df2.apply(get_clock_seconds_v2, axis=1)
print(f"\nRows with clock data: {df2['clock_seconds'].notna().sum()} / {len(df2)}")

df2["cp_loss_capped"] = df2["cp_loss"].clip(upper=1000)

def time_pressure_bucket(seconds):
    if seconds is None:
        return None
    elif seconds >= 60:
        return "comfortable (60s+)"
    elif seconds >= 30:
        return "getting low (30-60s)"
    elif seconds >= 10:
        return "low (10-30s)"
    else:
        return "critical (<10s)"

df2["time_bucket"] = df2["clock_seconds"].apply(time_pressure_bucket)

bucket_order = ["comfortable (60s+)", "getting low (30-60s)", "low (10-30s)", "critical (<10s)"]

counts = df2.groupby(["player_name", "time_bucket"]).size().reindex(
    pd.MultiIndex.from_product([df2["player_name"].unique(), bucket_order]), fill_value=0
)
print("\nMove counts per bucket:")
print(counts)

avg_by_bucket = df2.groupby(["player_name", "time_bucket"])["cp_loss_capped"].mean().reindex(
    pd.MultiIndex.from_product([df2["player_name"].unique(), bucket_order]), fill_value=None
)
print("\nAverage centipawn loss per bucket (capped):")
print(avg_by_bucket.round(1))

median_by_bucket = df2.groupby(["player_name", "time_bucket"])["cp_loss"].median().reindex(
    pd.MultiIndex.from_product([df2["player_name"].unique(), bucket_order]), fill_value=None
)
print("\nMedian centipawn loss per bucket:")
print(median_by_bucket.round(1))

df2.to_csv("chess_analysis_results_v2.csv", index=False)

critical_errors = df2[
    (df2["player_name"] == "DrNykterstein") &
    (df2["time_bucket"] == "critical (<10s)") &
    (df2["classification"].isin(["mistake", "blunder"]))
].sort_values("cp_loss", ascending=False)

print(f"Critical-time errors found: {len(critical_errors)} out of 175 critical-time moves")
print("-" * 50)
print(critical_errors[["game_id", "move_number", "move_san", "clock_seconds", "eval_before", "eval_after", "cp_loss", "classification"]].to_string())

critical_breakdown = df2[
    (df2["player_name"] == "DrNykterstein") &
    (df2["time_bucket"] == "critical (<10s)")
]["classification"].value_counts()

print("Classification breakdown for ALL critical-time moves:")
print(critical_breakdown)
print(f"\nAs percentages:")
print((critical_breakdown / critical_breakdown.sum() * 100).round(1))

games_with_critical_errors = critical_errors["game_id"].value_counts()
print("Which games contain these critical-time errors:")
print(games_with_critical_errors)

game_lengths = df2[df2["game_id"].isin(games_with_critical_errors.index)].groupby("game_id")["move_number"].max()
print("\nTotal move count for those games:")
print(game_lengths.sort_values(ascending=False))

DECIDED_THRESHOLD = 1000  # centipawns

df2["already_decided"] = df2["eval_before"].abs() >= DECIDED_THRESHOLD

meaningful = df2[~df2["already_decided"]]

print(f"Moves excluded as 'already decided': {df2['already_decided'].sum()} / {len(df2)}")
print("-" * 50)

avg_meaningful = meaningful[meaningful["player_name"] == "DrNykterstein"].groupby("time_bucket")["cp_loss_capped"].mean().reindex(bucket_order)
count_meaningful = meaningful[meaningful["player_name"] == "DrNykterstein"].groupby("time_bucket").size().reindex(bucket_order)

print("Average cp_loss by time bucket, EXCLUDING already-decided positions:")
print(pd.DataFrame({"avg_cp_loss": avg_meaningful.round(1), "move_count": count_meaningful}))

